### ISSUE TITLE
[Feature Request] 构建出跨平台二进制文件，并通过 GitHub Release / Home Brew 等平台进行分发

### ISSUE THREAD

**Issue by bestony** [chyroc/aliyundrive-cli#31]
构建出跨平台二进制文件，并通过 GitHub Release / Home Brew 等平台进行分发，便于用户安装。

**Comment by chyroc** [comment]
好想法

**Comment by chyroc** [comment]
done

release: https://github.com/chyroc/aliyundrive-cli/releases/tag/v0.12.0
