### ISSUE TITLE
退出aliyundirver-cli 后，控制台无法继续输入字符

### ISSUE THREAD

**Issue by cyatom01** [chyroc/aliyundrive-cli#37]
嗨，大牛：
   安装了你这个云cli，我exit 退出cli 后，发现命令行输入字符不回显，按回车都是命令提示符前面的用户目录信息。不知道您是否遇到此问题？

**Comment by hellojukay** [comment]
@dtcui 你好, 能不能看看你安装的是哪一个版本
```
 aliyundrive-cli --version
```
另外你是如何退出 cli 的，你当前的操作系统是什么？
